"""
Pydantic schemas for Demo Approval Workflow and Dual-Tier Governance.
Defines models for multi-tier approval cases, national code proposals,
procurement impact metrics, mapping previews, and demo approval actions.
"""

from enum import Enum
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field, ConfigDict

from app.schemas.material import SourceMaterialResponse
from app.schemas.hybrid_scoring import HybridClassification


class ApprovalStage(str, Enum):
    PENDING_L1 = "PENDING_L1"          # Awaiting Technical Nodal Officer verification
    PENDING_L2 = "PENDING_L2"          # Verified by L1, awaiting Ministry Authority ratification
    COMPLETED = "COMPLETED"            # Successfully approved and published
    REJECTED = "REJECTED"              # Rejected as distinct materials
    NEEDS_INFO = "NEEDS_INFO"          # Clarification or drawing requested


class ApprovalWorkflowStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED_AS_MASTER_ALIAS = "APPROVED_AS_MASTER_ALIAS"
    APPROVED_AS_UNIFIED_SKU = "APPROVED_AS_UNIFIED_SKU"
    REJECTED_DISTINCT = "REJECTED_DISTINCT"
    NEEDS_MORE_INFO = "NEEDS_MORE_INFO"


class ApprovalDecision(str, Enum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    NEEDS_MORE_INFO = "NEEDS_MORE_INFO"


class ProcurementImpact(BaseModel):
    """
    Estimated annual fiscal and operational impact of standardizing duplicate items.
    """
    duplicate_count: int = Field(default=2, description="Count of duplicate source SKUs being consolidated")
    estimated_annual_spend_overlap: float = Field(..., description="Estimated aggregate annual procurement spend (INR)")
    standardization_savings_percent: float = Field(..., description="Estimated percentage savings from catalog unification")
    estimated_savings_inr: float = Field(..., description="Estimated annual monetary savings in INR")
    affected_cpses: List[str] = Field(default_factory=list, description="Public sector enterprises holding duplicate records")
    procurement_risk_level: str = Field(..., description="Risk assessment: 'LOW', 'MEDIUM', or 'HIGH'")
    is_demo_estimate: bool = Field(default=True, description="Explicit indicator of demonstration calculation")

    model_config = ConfigDict(from_attributes=True)


class MappingPreview(BaseModel):
    """
    Preview of the proposed master-to-source canonical SKU mapping.
    """
    source_material_codes: List[str] = Field(default_factory=list, description="Source catalog item codes")
    source_cpses: List[str] = Field(default_factory=list, description="Associated source public sector enterprises")
    target_national_code: str = Field(..., description="Proposed canonical National Material Master code")
    target_description: str = Field(..., description="Standardized canonical description")
    mapping_type: str = Field(default="CATALOG_ALIAS", description="Mapping strategy: 'UNIFIED_CANONICAL' or 'CATALOG_ALIAS'")

    model_config = ConfigDict(from_attributes=True)


class ApprovalCase(BaseModel):
    """
    Comprehensive governance case record representing a candidate duplicate pair
    awaiting dual-tier review and canonical SKU proposal.
    """
    approval_case_id: str = Field(..., description="Unique deterministic case identifier")
    candidate_pair_id: str = Field(..., description="Referenced candidate duplicate pair ID")
    source_material_a: SourceMaterialResponse = Field(..., description="Primary incoming CPSE source material record")
    source_material_b: SourceMaterialResponse = Field(..., description="Candidate matching CPSE source material record")
    proposed_national_material_code: str = Field(..., description="Proposed national material code (e.g., NAMM-BRG-6205-2RS)")
    proposed_standard_description: str = Field(..., description="Proposed canonical standard nomenclature")
    hybrid_score: float = Field(..., ge=0.0, le=1.0, description="Calibrated composite hybrid duplicate score")
    hybrid_classification: HybridClassification = Field(..., description="Classification decision tier")
    explanation_summary: str = Field(..., description="Executive review rationale generated by explainability engine")
    required_approval_level: str = Field(..., description="Required workflow: 'L1_ONLY', 'L1_AND_L2', 'L2_SPECIALIST', or 'REJECTED_ONLY'")
    current_stage: ApprovalStage = Field(..., description="Current governance review stage")
    approval_status: ApprovalWorkflowStatus = Field(default=ApprovalWorkflowStatus.PENDING, description="Overall case status")
    l1_reviewer: Optional[str] = Field(default=None, description="Technical Nodal Officer name/id")
    l1_decision: Optional[str] = Field(default=None, description="L1 decision (APPROVE, REJECT, NEEDS_MORE_INFO)")
    l1_reviewed_at: Optional[str] = Field(default=None, description="ISO timestamp of L1 review")
    l1_notes: Optional[str] = Field(default=None, description="L1 reviewer remarks")
    l2_reviewer: Optional[str] = Field(default=None, description="Ministry Authority name/id")
    l2_decision: Optional[str] = Field(default=None, description="L2 decision")
    l2_reviewed_at: Optional[str] = Field(default=None, description="ISO timestamp of L2 review")
    l2_notes: Optional[str] = Field(default=None, description="L2 reviewer remarks")
    procurement_impact: ProcurementImpact = Field(..., description="Procurement impact and estimated savings metrics")
    mapping_preview: MappingPreview = Field(..., description="Proposed catalog mapping structure")
    created_at: str = Field(..., description="ISO timestamp of case creation")

    model_config = ConfigDict(from_attributes=True)


class ApprovalActionRequest(BaseModel):
    """
    Review action request payload submitted by Nodal Reviewers or Ministry Authorities.
    """
    approval_case_id: str = Field(..., description="Target approval case ID")
    decision: ApprovalDecision = Field(..., description="Decision: 'APPROVE', 'REJECT', or 'NEEDS_MORE_INFO'")
    reviewer_name: str = Field(default="Nodal Officer Sharma", description="Name of the officer")
    reviewer_role: str = Field(default="NODAL_OFFICER", description="'NODAL_OFFICER' (L1) or 'MINISTRY_AUTHORITY' (L2)")
    reviewer_note: Optional[str] = Field(default=None, description="Technical justification or remarks")
    stage: str = Field(default="L1_REVIEW", description="'L1_REVIEW' or 'L2_REVIEW'")


class ApprovalActionResponse(BaseModel):
    """
    Response model confirming receipt of approval action.
    Strictly non-persisted in demonstration prototype.
    """
    status: str = Field(default="demo_action_recorded", description="Status code")
    approval_case_id: str = Field(..., description="Evaluated approval case")
    decision: str = Field(..., description="Decision recorded")
    updated_case: ApprovalCase = Field(..., description="Updated state of approval case in memory")
    generated_audit_event: Dict[str, Any] = Field(..., description="Cryptographically signed audit event generated for this action")
    message: str = Field(
        default="Demo-only approval action processed in memory; not persisted to database.",
        description="Mandatory disclosure of non-persistence"
    )
    persisted: bool = Field(default=False, description="Guaranteed False in demo prototype mode")

    model_config = ConfigDict(from_attributes=True)


class ApprovalQueueResponse(BaseModel):
    total_cases: int = Field(..., description="Total approval cases in queue")
    pending_l1_count: int = Field(..., description="Cases awaiting L1 Nodal verification")
    pending_l2_count: int = Field(..., description="Cases awaiting L2 Ministry ratification")
    completed_count: int = Field(..., description="Cases resolved or approved")
    cases: List[ApprovalCase] = Field(default_factory=list, description="List of approval cases")
    version: str = Field(default="approval-workflow-v1.0")
    note: str = Field(default="Demo-only approval queue: data generated dynamically from sample pipeline without database persistence.")

    model_config = ConfigDict(from_attributes=True)
